# Override with --build-arg BASE_IMAGE=... to switch ROCm/Python version.
# Tested base images:
#   rocm/pytorch:rocm6.4.3_ubuntu22.04_py3.10_pytorch_release_2.5.1
#   rocm/pytorch:rocm7.1.1_ubuntu24.04_py3.12_pytorch_release_2.8.0
#   rocm/pytorch:rocm7.2.4_ubuntu22.04_py3.10_pytorch_release_2.8.0
#   rocm/pytorch:rocm7.2.4_ubuntu24.04_py3.12_pytorch_release_2.8.0
ARG BASE_IMAGE=rocm/pytorch:rocm7.2.4_ubuntu22.04_py3.10_pytorch_release_2.8.0
FROM ${BASE_IMAGE}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git ibverbs-utils libibverbs-dev \
    openmpi-bin libopenmpi-dev \
    libpci-dev libdw1 locales \
    libgrpc-dev libgrpc++-dev libprotobuf-dev protobuf-compiler-grpc \
    cmake && \
    rm -rf /var/lib/apt/lists/*
